---
- include_vars: ../creds.yml

- name: CentOS | Getting Public IP
  ipify_facts:
  register: public_ip
  when: 
    - hypervisor == 'gcp'

- name: CentOS | Setting Hostname
  hostname: name={{ inventory_hostname }}
  when: 
    - hypervisor == 'gcp'
    - not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

- name: CentOS | Adding hostname to /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^{{ ansible_default_ipv4.address }}.+$"
    line="{{ ipify_public_ip }} {{ inventory_hostname }}"
  when: 
    - hypervisor == 'gcp'

- name: CentOS | Installing required packages
  yum:
    name: "{{ linux_prereq_packages }}"

- name: CentOS | Updating packages
  yum:
    name: "*"
    state: latest
  tags:
    - skip_ansible_lint   # Updating packages is a requirement

- name: CentOS | Rebooting servers
  reboot: