---
- name: Init | Powering on VMs
  vmware_guest:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    validate_certs: false
    name: "{{ item }}"
    state: poweredon
  loop: "{{ groups['nodes'] }}"

- name: Init | Checking if SSH key already exists
  stat:
    path: ~/.ssh/k8s
  register: stat_result

- name: Init | Generating SSH key
  command: ssh-keygen -q -t rsa -f ~/.ssh/k8s -C "" -N ""
  args:
    creates: ~/.ssh/k8s
  when: not stat_result.stat.exists

- name: Init | Adding SSH key to authorized keys
  command: ssh-add -K ~/.ssh/k8s

- name: Init | Waiting for VMs to come online
  wait_for:
    port: 22
    delay: 5
    host: "{{ hostvars[item]['ansible_host'] }}"
  loop: "{{ groups['nodes'] }}"
  register: power_on
  async: 1000
  poll: 0

- name: "Init | Waiting for VMs to finish starting"
  async_status:
     jid: "{{ item.ansible_job_id }}"
  register: results
  retries: 500
  delay: 5
  until: results.finished
  loop: "{{ power_on.results }}"