---
- name: Preparing OpenShift Nodes
  hosts: nodes
  gather_facts: true
  become: true

  roles:
    - role: centos/ssh
      when: 
       - hypervisor == 'esxi'
       - operating_system == 'centos'
    - role: centos/install
      when: operating_system == 'centos'